### PR TITLE
Refactor and Dockerise

### PR DESCRIPTION
**Pull request by rajyraman**

### CODE REVIEW

**Comment by BetimBeja** [comment]
Hello @rajyraman ,
the last version rajyraman/Levelup-for-Dynamics-CRM@b6873fff631d5fd5d18f234b9ee882084f131bfe the command `docker-compose up` ends in error stating that it can't find the image `levelup-for-dynamics-365-powerapps`...
If I remove `current` and `latest` from the [docker-compose.yml](/rajyraman/Levelup-for-Dynamics-CRM/blob/b6873fff631d5fd5d18f234b9ee882084f131bfe/docker-compose.yml) file it compiles successfully. Is this a bug or am I missing some step?

Best regards,
Betim.

**Comment by rajyraman** [comment]
@BetimBeja - Try ` docker-compose  up -d --build`. Install the Docker extension on VSCode (https://code.visualstudio.com/docs/containers/overview). Makes it lot easier than remembering commands.

**Comment by BetimBeja** [comment]
I get the following error...
image
Perhaps `levelup-for-dynamics-365-powerapps` is not a public image?

**Comment by rajyraman** [comment]
@BetimBeja - Getting the same error after deleting the local images. Try using this compose file for the moment. I will check this in the next commit.

`version: '3.4'

x-levelup:
  &default-levelup
  build: .
  volumes:
    - type: bind
      source: ./packages
      target: /usr/src/levelup/packages
    - type: bind
      source: ./dist
      target: /usr/src/levelup/dist
  image: levelup-for-dynamics-365-powerapps     
services:
  current:
    << : *default-levelup
    image: levelup-for-dynamics-365-powerapps:3.5.0
  latest:
    *default-levelup`

**Pull request merged**
